# Generated by Django 5.1.7 on 2025-03-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=128, null=True)),
                ('time', models.CharField(max_length=128, null=True)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('quantity', models.CharField(max_length=128, null=True)),
                ('is_buyer_maker', models.BooleanField(null=True)),
            ],
        ),
    ]
